# Generated by Django 5.2.8 on 2025-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(blank=True, help_text='Name of the Kaggle project', max_length=50)),
                ('prj_image', models.ImageField(blank=True, help_text='Project thumbnail image', null=True, upload_to='projects/images/')),
                ('launched_at', models.DateField(blank=True, help_text='Project launch date', null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Detailed project description')),
                ('metric', models.TextField(blank=True, help_text='Evaluation metric used in competition')),
                ('data_type', models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('SIGNAL', 'Signal'), ('TEXT', 'Text'), ('TABULAR', 'Tabular')], help_text='Type of data used in project', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-launched_at'],
            },
        ),
    ]
