# Generated by Django 5.2.8 on 2025-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-is_featured', '-start_date', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='launched_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='prj_image',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='prj_name',
        ),
        migrations.AddField(
            model_name='projects',
            name='accuracy_score',
            field=models.FloatField(blank=True, help_text='Best accuracy or main metric score', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image paths'),
        ),
        migrations.AddField(
            model_name='projects',
            name='business_problem',
            field=models.TextField(blank=True, help_text='What business/problem does this solve?'),
        ),
        migrations.AddField(
            model_name='projects',
            name='challenges',
            field=models.TextField(blank=True, help_text='Technical challenges faced and solutions'),
        ),
        migrations.AddField(
            model_name='projects',
            name='dataset_url',
            field=models.URLField(blank=True, help_text='Dataset source URL'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default='None', help_text='Detailed project description and overview'),
        ),
        migrations.AddField(
            model_name='projects',
            name='difficulty_level',
            field=models.CharField(choices=[('BEGINNER', '⭐ Beginner'), ('INTERMEDIATE', '⭐⭐ Intermediate'), ('ADVANCED', '⭐⭐⭐ Advanced'), ('EXPERT', '⭐⭐⭐⭐ Expert')], default='INTERMEDIATE', help_text='Project difficulty level', max_length=15),
        ),
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end date', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='evaluation_metric',
            field=models.CharField(blank=True, help_text='Evaluation metric used (e.g., RMSE, Accuracy, F1-Score)', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main project thumbnail image', null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this project on homepage'),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show this project publicly'),
        ),
        migrations.AddField(
            model_name='projects',
            name='kaggle_rank',
            field=models.IntegerField(blank=True, help_text='Kaggle competition rank (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='kaggle_url',
            field=models.URLField(blank=True, help_text='Kaggle notebook/competition URL'),
        ),
        migrations.AddField(
            model_name='projects',
            name='key_achievements',
            field=models.TextField(blank=True, help_text='Key results and achievements'),
        ),
        migrations.AddField(
            model_name='projects',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='What did you learn from this project?'),
        ),
        migrations.AddField(
            model_name='projects',
            name='libraries_used',
            field=models.TextField(blank=True, help_text='Specific libraries and tools used'),
        ),
        migrations.AddField(
            model_name='projects',
            name='live_demo_url',
            field=models.URLField(blank=True, help_text='Live demo URL (if available)'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('KAGGLE_COMPETITION', '🏆 Kaggle Competition'), ('PERSONAL_PROJECT', '🤖 Personal ML Project'), ('DATA_ANALYSIS', '📈 Data Analysis'), ('DATA_VISUALIZATION', '🎨 Data Visualization'), ('DEEP_LEARNING', '🧠 Deep Learning'), ('NLP_PROJECT', '💬 NLP Project'), ('TIME_SERIES', '⏰ Time Series Analysis'), ('ACADEMIC', '🎓 Academic Project'), ('WORK', '💼 Work Project')], default='NONE', help_text='Type of project', max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief one-line description', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='skills_used',
            field=models.JSONField(default=list, help_text="List of skills used (e.g., ['PYTHON', 'SKLEARN', 'PANDAS'])"),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='technical_approach',
            field=models.TextField(blank=True, help_text='Technical methodology and approach'),
        ),
        migrations.AddField(
            model_name='projects',
            name='time_spent',
            field=models.CharField(blank=True, help_text="Estimated time spent (e.g., '2 weeks', '3 months')", max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default=None, help_text="Project title (e.g., 'House Price Prediction')", max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='total_competitors',
            field=models.IntegerField(blank=True, help_text='Total competitors in Kaggle competition', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='data_type',
            field=models.CharField(choices=[('TABULAR', 'Tabular Data'), ('IMAGE', 'Image Data'), ('TEXT', 'Text Data'), ('TIME_SERIES', 'Time Series Data'), ('AUDIO', 'Audio Data'), ('VIDEO', 'Video Data'), ('MULTIMODAL', 'Multimodal Data')], help_text='Type of data used in project', max_length=15),
        ),
        migrations.AlterField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['project_type', 'is_public'], name='projects_pr_project_d4a411_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['is_featured', 'is_public'], name='projects_pr_is_feat_4cbf37_idx'),
        ),
    ]
