# Generated by Django 5.2.8 on 2025-11-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_skills_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='input_features',
            field=models.JSONField(default=list, help_text='List of input features for the model'),
        ),
        migrations.AddField(
            model_name='projects',
            name='model_type',
            field=models.CharField(blank=True, choices=[('CLASSIFICATION', 'Classification'), ('REGRESSION', 'Regression'), ('CLUSTERING', 'Clustering'), ('NLP', 'Natural Language Processing'), ('SIGNAL', 'Signal Processing'), ('BIOSIGNAL', 'Biosignal Processing'), ('COMPUTER_VISION', 'Computer Vision')], help_text='Type of machine learning model', max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='prediction_endpoint',
            field=models.BooleanField(default=False, help_text='Enable prediction page for this project'),
        ),
        migrations.AddField(
            model_name='projects',
            name='target_feature',
            field=models.CharField(blank=True, help_text='Target variable name', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='trained_model',
            field=models.FileField(blank=True, help_text='Trained model file (pickle, h5, joblib)', null=True, upload_to='projects/models/'),
        ),
    ]
