# Generated by Django 5.2.8 on 2025-11-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_input_features_projects_model_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='input_features',
            field=models.JSONField(blank=True, default=list, help_text='List of input features for the model'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='model_type',
            field=models.CharField(blank=True, choices=[('CLASSIFICATION', 'Classification'), ('REGRESSION', 'Regression'), ('CLUSTERING', 'Clustering'), ('NLP', 'Natural Language Processing'), ('COMPUTER_VISION', 'Computer Vision')], help_text='Type of machine learning model', max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='skills_used',
            field=models.JSONField(default=list, help_text="List of skills used (e.g., ['PYTHON', 'SKLEARN', 'PANDAS'])"),
        ),
    ]
