# Generated by Django 5.2.8 on 2025-11-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_input_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills_used',
            field=models.CharField(default="'PYTHON', 'SKLEARN', 'PANDAS'", help_text="List of skills used (e.g., ['PYTHON', 'SKLEARN', 'PANDAS'])"),
        ),
    ]
