# Generated by Django 5.2.8 on 2025-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projects_skills_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills_used',
            field=models.JSONField(blank=True, default=list, help_text="List of skills used (e.g., ['PYTHON', 'SKLEARN', 'PANDAS'])"),
        ),
    ]
