# Generated by Django 5.2.8 on 2025-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projects_skills_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills_used',
            field=models.JSONField(choices=[('PYTHON', 'Python'), ('R', 'R Programming'), ('SQL', 'SQL & Databases'), ('PANDAS', 'Pandas'), ('NUMPY', 'NumPy'), ('SKLEARN', 'Scikit-learn'), ('TENSORFLOW', 'TensorFlow'), ('PYTORCH', 'PyTorch'), ('KERAS', 'Keras'), ('XGBOOST', 'XGBoost'), ('LIGHTGBM', 'LightGBM'), ('MATPLOTLIB', 'Matplotlib'), ('SEABORN', 'Seaborn'), ('PLOTLY', 'Plotly'), ('OPENCV', 'OpenCV'), ('NLTK', 'NLTK'), ('SPACY', 'spaCy'), ('HUGGINGFACE', 'Hugging Face'), ('DOCKER', 'Docker'), ('AWS', 'AWS'), ('GCP', 'Google Cloud'), ('AZURE', 'Microsoft Azure')], help_text="List of skills used (e.g., ['PYTHON', 'SKLEARN', 'PANDAS'])"),
        ),
    ]
