# Generated by Django 5.2.8 on 2025-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projects_skills_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills_used',
            field=models.TextField(blank=True, help_text='Enter skills as comma-separated values from the predefined list'),
        ),
    ]
