# Generated by Django 5.2.12 on 2026-03-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projects_prediction_input_type_file_input_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='input_features',
            field=models.JSONField(blank=True, default=list, help_text='List of input features for manual form entry'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='prediction_input_type',
            field=models.CharField(choices=[('manual', 'Manual feature entry (form fields)'), ('file', 'File upload (CSV, EDF, JSON signal)')], default='file', help_text='How the user provides input data for prediction', max_length=10),
        ),
    ]
