# Generated by Django 5.2.12 on 2026-03-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projects_input_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file_input_config',
            field=models.JSONField(blank=True, default={'accepted_formats': ['csv', 'edf', 'json'], 'description': 'Upload a 1-second EEG segment (22 channels, 256 Hz)', 'example_columns': ['Fp1', 'Fp2', 'F3'], 'label_map': {'0': 'No seizure', '1': 'Seizure detected'}, 'preprocessing': 'bandpower'}, help_text='Configuration for file-based prediction input (JSON)'),
        ),
    ]
