# Generated by Django 5.2.12 on 2026-03-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projects_file_input_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file_input_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for file-based prediction input (JSON)'),
        ),
    ]
