# Generated by Django 5.2.12 on 2026-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_projects_prediction_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='accuracy_score',
            field=models.FloatField(blank=True, help_text='Best accuracy or primary metric score (0–1 or 0–100)', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='business_problem',
            field=models.TextField(blank=True, help_text='What business or research problem does this solve?'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='challenges',
            field=models.TextField(blank=True, help_text='Technical challenges faced and how they were solved'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='data_type',
            field=models.CharField(blank=True, choices=[('TABULAR', 'Tabular Data'), ('IMAGE', 'Image Data'), ('TEXT', 'Text Data'), ('TIME_SERIES', 'Time Series Data'), ('AUDIO', 'Audio Data'), ('VIDEO', 'Video Data'), ('MULTIMODAL', 'Multimodal Data')], help_text='Type of data used in the project', max_length=15),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Full project description and overview'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='difficulty_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', help_text='Project difficulty level', max_length=15),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end date (leave blank if ongoing)', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='evaluation_metric',
            field=models.CharField(blank=True, help_text='Metric name, e.g.: F1-Score, RMSE, AUC-ROC', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image shown on project cards', null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file_input_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for file-upload demo. Must include "handler" slug. See projects/inference/ADMIN_CONFIGS.md for ready-to-paste examples.'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='input_features',
            field=models.JSONField(blank=True, default=list, help_text='List of input fields for manual mode. Example: [{"name": "age", "type": "number", "description": "Patient age"}]'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin this project to the homepage featured section'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show this project to visitors'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='kaggle_rank',
            field=models.IntegerField(blank=True, help_text='Kaggle competition final rank', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='live_demo_url',
            field=models.URLField(blank=True, help_text='Live demo URL (if deployed separately)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='prediction_endpoint',
            field=models.BooleanField(default=False, help_text='Enable the prediction demo page for this project'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='prediction_input_type',
            field=models.CharField(choices=[('manual', 'Manual — form fields'), ('file', 'File upload')], default='file', help_text='How the user provides data: upload a file OR fill in form fields', max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.CharField(blank=True, choices=[('KAGGLE_COMPETITION', 'Kaggle Competition'), ('PERSONAL_PROJECT', 'Personal ML Project'), ('DATA_ANALYSIS', 'Data Analysis'), ('DATA_VISUALIZATION', 'Data Visualization'), ('DEEP_LEARNING', 'Deep Learning'), ('NLP_PROJECT', 'NLP Project'), ('TIME_SERIES', 'Time Series Analysis'), ('ACADEMIC', 'Academic Project'), ('WORK', 'Work Project')], help_text='Type of project', max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_description',
            field=models.CharField(blank=True, help_text='One-line summary shown on cards and the demo page', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='skills_used',
            field=models.TextField(blank=True, help_text='Comma-separated skill keys, e.g.: PYTHON, PYTORCH, SKLEARN'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='target_feature',
            field=models.CharField(blank=True, help_text="Target variable name shown on the demo page (e.g., 'seizure')", max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='time_spent',
            field=models.CharField(blank=True, help_text="Estimated time spent, e.g.: '3 months', '2 weeks'", max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(help_text="Project title (e.g., 'EEG Seizure Detection')", max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_competitors',
            field=models.IntegerField(blank=True, help_text='Total number of competitors (for percentile calculation)', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='trained_model',
            field=models.FileField(blank=True, help_text='Trained model file (.pkl, .joblib, .h5, .pt)', null=True, upload_to='projects/models/'),
        ),
    ]
