# Generated by Django 5.2.12 on 2026-03-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projects_accuracy_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='rag_document',
            field=models.FileField(blank=True, help_text='Upload a PDF, Word, Text, or Markdown file containing detailed project documentation. This file will be used by the RAG system to provide richer AI interpretations. Supported formats: .pdf, .docx, .txt, .md', null=True, upload_to='projects/rag_documents/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='rag_document_processed',
            field=models.BooleanField(default=False, help_text='Whether the document has been processed by the RAG system'),
        ),
        migrations.AddField(
            model_name='projects',
            name='rag_document_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the RAG document was last uploaded', null=True),
        ),
    ]
