# Generated by Django 5.2.12 on 2026-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='avg_inference_ms',
            field=models.IntegerField(blank=True, help_text='Average inference latency in milliseconds (shown on card)', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='ci_cd_badge_url',
            field=models.URLField(blank=True, help_text='GitHub Actions badge image URL (e.g. https://github.com/user/repo/actions/workflows/ci.yml/badge.svg)'),
        ),
        migrations.AddField(
            model_name='projects',
            name='has_api',
            field=models.BooleanField(default=False, help_text='Check if this project exposes a REST API endpoint'),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_dockerized',
            field=models.BooleanField(default=False, help_text='Check if this project has a Dockerfile / is containerised'),
        ),
    ]
