# Generated by Django 5.2.12 on 2026-04-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_add_mlops_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='experiment_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Final metrics logged. e.g. {"val_accuracy":0.966,"f1":0.94,"auc":0.98}'),
        ),
        migrations.AddField(
            model_name='projects',
            name='experiment_params',
            field=models.JSONField(blank=True, default=dict, help_text='Key hyperparameters logged (shown on detail page). e.g. {"epochs":50,"lr":0.001,"batch_size":32}'),
        ),
        migrations.AddField(
            model_name='projects',
            name='mlflow_run_id',
            field=models.CharField(blank=True, help_text='MLflow run ID for this model version', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='mlflow_tracking_url',
            field=models.URLField(blank=True, help_text='Link to MLflow UI for this experiment'),
        ),
    ]
