# Generated by Django 5.2.12 on 2026-04-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_mlflow_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRAGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Supported: PDF, Word, TXT, MD, Python (.py), Notebook (.ipynb)', upload_to='projects/rag_files/')),
                ('label', models.CharField(blank=True, help_text='Optional label, e.g. "Thesis", "Training script", "Analysis notebook"', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_files', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Project RAG File',
                'verbose_name_plural': 'Project RAG Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
