# Generated by Django 5.2.8 on 2025-11-14 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('SPAM', 'Spam')], default='NEW', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GITHUB', 'GitHub'), ('LINKEDIN', 'LinkedIn'), ('KAGGLE', 'Kaggle'), ('EMAIL', 'Email'), ('TWITTER', 'Twitter'), ('PORTFOLIO', 'Portfolio'), ('OTHER', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(help_text='How it appears on website', max_length=100)),
                ('icon_class', models.CharField(default='fas fa-link', help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Short description for this contact method')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which contacts appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Profile',
                'verbose_name_plural': 'Contact Profiles',
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_email', models.EmailField(default='seyedhasan.mirhoseini1367@gmail.com', max_length=254)),
                ('contact_email', models.EmailField(help_text='Where contact form messages are sent', max_length=254)),
                ('response_time', models.CharField(default='24-48 hours', max_length=50)),
                ('availability_status', models.BooleanField(default=True)),
                ('availability_message', models.TextField(default="I'm currently available for new opportunities and collaborations.")),
            ],
            options={
                'verbose_name': 'Contact Setting',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
    ]
