# Generated by Django 5.2.8 on 2025-12-02 15:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag (max 50 characters)', max_length=50, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Brief description of the tag', max_length=300, verbose_name='Tag Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a descriptive title (max 200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(10, message='Title must be at least 10 characters long.'), django.core.validators.MaxLengthValidator(200, message='Title cannot exceed 200 characters.')], verbose_name='Story Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of the title', max_length=250, unique_for_date='published_at', verbose_name='URL Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary of the story (max 500 characters)', max_length=500, verbose_name='Short Excerpt')),
                ('content', models.TextField(help_text='Write your story here', verbose_name='Story Content')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('AR', 'Archived')], default='DF', help_text='Current status of the story', max_length=2, verbose_name='Publication Status')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional image to accompany the story', null=True, upload_to='stories/%Y/%m/%d/', verbose_name='Featured Image')),
                ('read_time_minutes', models.PositiveIntegerField(default=0, help_text='Auto-calculated reading time', verbose_name='Estimated Read Time (minutes)')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this story has been viewed', verbose_name='View Count')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Like Count')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark this story as featured to highlight it', verbose_name='Featured Story')),
                ('allow_comments', models.BooleanField(default=True, help_text='Enable or disable comments for this story', verbose_name='Allow Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when the story was published', null=True, verbose_name='Published At')),
                ('author', models.ForeignKey(help_text='The user who wrote this story', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', models.ManyToManyField(blank=True, help_text='Categorize your story with relevant tags', related_name='stories', to='stories.tag', verbose_name='Story Tags')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Write your comment here', validators=[django.core.validators.MinLengthValidator(10, message='Comment must be at least 10 characters.')], verbose_name='Comment Content')),
                ('is_approved', models.BooleanField(default=True, help_text='Approve or reject this comment', verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment Author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.comment', verbose_name='Parent Comment')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story', verbose_name='Story')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['story', 'created_at'], name='stories_com_story_i_8bb17a_idx'), models.Index(fields=['is_approved'], name='stories_com_is_appr_99746a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='stories.story')),
            ],
            options={
                'verbose_name': 'Story View',
                'verbose_name_plural': 'Story Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['story', 'viewed_at'], name='stories_sto_story_i_0063d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-published_at'], name='stories_sto_publish_3f0ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status'], name='stories_sto_status_e72f11_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author'], name='stories_sto_author__45d8bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DF', 'PB', 'AR'])), name='valid_story_status'),
        ),
    ]
