# Generated by Django 5.2.8 on 2025-12-02 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story Like',
                'verbose_name_plural': 'Story Likes',
                'indexes': [models.Index(fields=['story', 'user'], name='stories_sto_story_i_19b94a_idx'), models.Index(fields=['created_at'], name='stories_sto_created_1151c3_idx')],
                'unique_together': {('story', 'user')},
            },
        ),
    ]
