# Generated by Django 5.2.12 on 2026-04-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0019_add_mlops_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=1.0, help_text='0.0–1.0')),
                ('avg_latency_ms', models.FloatField(blank=True, null=True)),
                ('avg_confidence', models.FloatField(blank=True, null=True)),
                ('confidence_std', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='projects.projects')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Sanitised input sent to model')),
                ('input_type', models.CharField(default='manual', max_length=20)),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('inference_ms', models.IntegerField(blank=True, help_text='Inference latency in milliseconds', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.CharField(default='web', help_text='web | api | demo', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='projects.projects')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='monitoring__project_bda180_idx'), models.Index(fields=['created_at'], name='monitoring__created_4e6584_idx')],
            },
        ),
    ]
