# Generated by Django 5.2.8 on 2025-11-14 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('PHD', 'PhD'), ('CERTIFICATION', 'Certification'), ('DIPLOMA', 'Diploma')], max_length=20)),
                ('field_of_study', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-end_date', '-start_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.JSONField(default=list, help_text='List of key achievements/responsibilities')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['-end_date', '-start_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('PERSIAN', 'Persian'), ('FINNISH', 'Finnish'), ('ARABIC', 'Arabic')], max_length=20)),
                ('proficiency', models.CharField(choices=[('NATIVE', 'Native'), ('FLUENT', 'Fluent'), ('PROFESSIONAL', 'Professional Working Proficiency'), ('INTERMEDIATE', 'Intermediate'), ('BEGINNER', 'Beginner')], max_length=15)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies_used', models.JSONField(default=list, help_text='List of technologies used')),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Highlight',
                'verbose_name_plural': 'Project Highlights',
                'ordering': ['-end_date', '-start_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Seyed Hasan Mirhoseini', max_length=100)),
                ('job_title', models.CharField(default='Junior Data Scientist', max_length=100)),
                ('email', models.EmailField(default='seyedhasan.mirhoseini1367@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(default='Tampere, Finland', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('professional_summary', models.TextField(default='Passionate Junior Data Scientist with expertise in machine learning, data analysis, and building predictive models. Strong background in Python, SQL, and data visualization tools.', help_text='Your professional summary/objective')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('kaggle_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Setting',
                'verbose_name_plural': 'Resume Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming Languages'), ('ML_FRAMEWORKS', 'ML & AI Frameworks'), ('DATA_ANALYSIS', 'Data Analysis'), ('DATA_VISUALIZATION', 'Data Visualization'), ('DATABASES', 'Databases'), ('CLOUD', 'Cloud & DevOps'), ('TOOLS', 'Tools & Platforms'), ('SOFT_SKILLS', 'Soft Skills')], max_length=20)),
                ('proficiency', models.IntegerField(default=1, help_text='Proficiency level from 1 (Beginner) to 5 (Expert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
