# Generated by Django 5.2.8 on 2025-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthighlight',
            name='technologies_used',
            field=models.JSONField(default=list, help_text='List of technologies used ["Python", "Django", "React", "PostgreSQL", "Docker", "Scikit-learn"]'),
        ),
    ]
