# Generated by Django 5.2.12 on 2026-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_projecthighlight_technologies_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesetting',
            name='cv_pdf',
            field=models.FileField(blank=True, help_text='Upload your CV as PDF to enable the Download CV button on the resume page', null=True, upload_to='resume/'),
        ),
    ]
