# Generated by Django 5.2.12 on 2026-04-13 07:37

import django.db.models.deletion
from django.db import migrations, models


def link_existing_records(apps, schema_editor):
    """Point all existing resume records to the first ResumeSetting (singleton)."""
    ResumeSetting   = apps.get_model('resume', 'ResumeSetting')
    setting = ResumeSetting.objects.first()
    if not setting:
        return
    for model_name in ('Education', 'Experience', 'Skill', 'ProjectHighlight', 'Certification', 'Language'):
        Model = apps.get_model('resume', model_name)
        Model.objects.filter(resume__isnull=True).update(resume=setting)


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_add_cv_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resume.resumesetting'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='resume.resumesetting'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='resume.resumesetting'),
        ),
        migrations.AddField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.resumesetting'),
        ),
        migrations.AddField(
            model_name='projecthighlight',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_highlights', to='resume.resumesetting'),
        ),
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='resume.resumesetting'),
        ),
        migrations.RunPython(link_existing_records, migrations.RunPython.noop),
    ]
